// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "song_metadata")]
pub struct SongMetadata {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: i64,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub song_id: i64,
    #[sqlx_gen(sql_type = "TEXT")]
    pub recording_date: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub genre: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub composer: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub audio_bitrate: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub bit_depth: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub channels: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub sample_rate: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub duration_ms: Option<i64>,
    #[sqlx_gen(sql_type = "DATETIME", column_default = "CURRENT_TIMESTAMP")]
    pub created_at: NaiveDateTime,
    #[sqlx_gen(sql_type = "DATETIME", column_default = "CURRENT_TIMESTAMP")]
    pub updated_at: NaiveDateTime,
}
