// Auto-generated by sqlx-gen. Do not edit.

#![allow(unused_attributes)]

use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};
use sqlx_gen::SqlxGen;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, sqlx::FromRow, SqlxGen)]
#[sqlx_gen(kind = "table", schema = "main", table = "songs")]
pub struct Songs {
    #[sqlx_gen(primary_key, sql_type = "INTEGER")]
    pub id: i64,
    #[sqlx_gen(sql_type = "TEXT")]
    pub filepath: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub hash: String,
    #[sqlx_gen(sql_type = "TEXT")]
    pub track_title: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub track_artist: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub track_lyricist: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub album_artist: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub album_title: Option<String>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub disc_number: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub track_number: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub track_total: Option<i64>,
    #[sqlx_gen(sql_type = "INTEGER")]
    pub disc_total: Option<i64>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub album_title_sort_order: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub album_artist_sort_order: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub track_title_sort_order: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub track_artist_sort_order: Option<String>,
    #[sqlx_gen(sql_type = "TEXT")]
    pub thumbnail_id: Option<String>,
    #[sqlx_gen(sql_type = "DATETIME", column_default = "CURRENT_TIMESTAMP")]
    pub created_at: NaiveDateTime,
    #[sqlx_gen(sql_type = "DATETIME", column_default = "CURRENT_TIMESTAMP")]
    pub updated_at: NaiveDateTime,
}
